### ISSUE TITLE
Missing citation details

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#19]
review phase: 3
level: enhancement 
type: content
ref: all (pdf)

### Reason (if not obvious)? 

In a scientific work that is as long as your thesis you need to provide more details for your citations, especially page and line numbers.

**Comment by lucendio** [comment]
I am not sure to what you referring to, but I made some changes to all inline and block quotations the other day. could you have another look into the content, maybe that would suffice your comment. otherwise, please give an example.

**Comment by 0ndorio** [comment]
Look got to me.
