### ISSUE TITLE
Missing bibliography details

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#20]
review phase: 3
level: enhancement 
type: content
ref: bibliography

### Reason (if not obvious)? 

Some of your bibliography entries are missing necessary information, i.e
 
> [44] Zaïane, Osmar R: Principles of knowledge discovery in databases, 1999 – scale
> [120] Neumann, Linus: Stellungnahme zum elektronischen rechtsverkehr.
> [122] Dean, Eeffrey ; Ghemawat, Sanjay: MapRednce: Simplified data
processing on large clusters (2004)

**Comment by lucendio** [comment]
addressed in https://github.com/lucendio/pdaas_thesis/commit/1a23b6e7101978654e71f784cb118816db3074d4
