### ISSUE TITLE
[110] Rephrasing line 21 

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#21]
review phase: 3
level: opinion 
type: phrasing
ref: *110*
line: *21*

### Reason (if not obvious)? 

Rephrase: 

> "When interacting directly with each other, discrimination of human beings is a serious issue in our society [...]."

Discrimination is not only a problem in direct interaction but also in a persons general mindset and in any kind of social interaction.

**Comment by lucendio** [comment]
partialy addressed in https://github.com/lucendio/pdaas_thesis/commit/e8f7dc6fabf592e4827768f981851950c0107f94

the reference to peoples mindsets (indirectly as a reason/problem) is mentioned later on (in the first chapter), when possible (non-technical) approaches are suggested.
