### ISSUE TITLE
Improve figure descriptions

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#23]
review phase: 3
level: opinion 
type: content
ref: all

### Reason (if not obvious)?
 
As far as I am concerned the descriptions of a figure should not only contain the name but also a short description of the image. This increases their meaningfulness and allows a potential reader to understand them, so that he doesn't need to scan the text to find the actual related section.

**Comment by lucendio** [comment]
technically possible, but debatable. I am able to add more text to a figure name with different level of emphasising, e.g.

```
![__PDaaS Architecture, centralized composition__ some more text](./assets/figures/pdaas_component-composition_centralized.png){#fig:composition-centralized}
```
but then the whole description is in the ToF as well, which is not desired. so either I leave the description as minimalistic as is (with minor changes) and as close to then mentioning in the text or I remove the ToF. I rather prefer the first approach.

**Comment by 0ndorio** [comment]
Already the second issue where you mention that you have to work around a limitation of your conversion tool. 👎  And removing the ToF is no option so keep the short descriptions.
