### ISSUE TITLE
[140] Use of interaction-language in the scenario description 

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#25]
review phase: 3
level: opinion 
type: phrasing
ref: 140

Some parts of the scenario descriptions do not sound like proper scientific-language. You may either rephrase them or add an additional paragraph in the beginning of the section where you mention that the interaction-language used in the following parts is by design to increase the intelligibility.

**Comment by lucendio** [comment]
addressed in https://github.com/lucendio/pdaas_thesis/commit/2a75d7b199ea9da3fa101d606e2576ed85f1603c
