### ISSUE TITLE
First occurrence of abbreviations

### ISSUE THREAD

**Issue by 0ndorio** [lucendio/pdaas_thesis#35]
review phase: 3
level: opinion 
type: content
ref: everything

I would suggest to change your abbreviation style a bit. It's much more convenient to write at least once the long version with the short one in bracers before you use the short version as stand alone. It's much harder to follow if the reader needs to stop and look into the footnotes to understand the abbreviation.

**Comment by lucendio** [comment]
partialy applied, only for appreviation that appear multiple times and more important ones
